# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import os
from controller.LoginController import LoginController
actualPath = os.getcwd()+"/src/sources/QT Design/qrc"
sys.path.append(actualPath)

import imgs_qrc_rc

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(371, 300)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        Form.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.frame.setFont(font)
        self.frame.setStyleSheet("background-color: rgb(229, 217, 209);\n"
"font: 8pt \"Courier\";")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(90, 160, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(90, 200, 81, 16))
        self.label_3.setObjectName("label_3")
        self.inputCorreo = QtWidgets.QLineEdit(self.frame)
        self.inputCorreo.setGeometry(QtCore.QRect(180, 160, 131, 20))
        self.inputCorreo.setObjectName("inputCorreo")
        self.inputContrasena = QtWidgets.QLineEdit(self.frame)
        self.inputContrasena.setGeometry(QtCore.QRect(180, 200, 131, 20))
        self.inputContrasena.setObjectName("inputContrasena")
        self.buttonEnviar = QtWidgets.QPushButton(self.frame)
        self.buttonEnviar.setGeometry(QtCore.QRect(160, 260, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.buttonEnviar.setFont(font)
        self.buttonEnviar.setStyleSheet("")
        self.buttonEnviar.setObjectName("buttonEnviar")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(150, 20, 101, 101))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/images/logo.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.frame)

        self.buttonEnviar.clicked.connect(self.sendData)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Login"))
        self.label_2.setText(_translate("Form", "Correo"))
        self.label_3.setText(_translate("Form", "Contraseña"))
        self.buttonEnviar.setText(_translate("Form", "Enviar"))

    def sendData(self):
        loginController = LoginController()
        correo= self.inputCorreo.text().strip()
        contraseña= self.inputContrasena.text().strip()
        
        loginController.controlador(correo,contraseña)
